-- Additive feedback, evaluation, and consented research analytics schema.
-- Keep prior migrations immutable. Application code owns value allowlists.

CREATE TABLE evaluation_campaigns (
  id BIGINT NOT NULL AUTO_INCREMENT,
  slug VARCHAR(100) NOT NULL,
  name VARCHAR(191) NOT NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'draft',
  data_scope VARCHAR(16) NOT NULL DEFAULT 'pilot',
  questionnaire_version VARCHAR(64) NOT NULL,
  consent_notice_version VARCHAR(64) NOT NULL,
  eligible_member_count INT NULL,
  starts_at TIMESTAMP NULL,
  ends_at TIMESTAMP NULL,
  retention_until TIMESTAMP NULL,
  opened_at TIMESTAMP NULL,
  closed_at TIMESTAMP NULL,
  locked_at TIMESTAMP NULL,
  created_by INT NULL,
  updated_by INT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_evaluation_campaigns_slug (slug),
  KEY idx_evaluation_campaigns_status_scope (status, data_scope, starts_at, ends_at),
  KEY idx_evaluation_campaigns_retention (retention_until),
  KEY idx_evaluation_campaigns_created_by (created_by),
  KEY idx_evaluation_campaigns_updated_by (updated_by),
  CONSTRAINT fk_evaluation_campaigns_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT fk_evaluation_campaigns_updated_by FOREIGN KEY (updated_by) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE analytics_consents (
  user_id INT NOT NULL,
  subject_key CHAR(64) NOT NULL,
  key_version INT NOT NULL DEFAULT 1,
  notice_version VARCHAR(64) NOT NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'active',
  consented_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  withdrawn_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id),
  UNIQUE KEY uq_analytics_consents_subject (subject_key),
  KEY idx_analytics_consents_status_updated (status, updated_at),
  CONSTRAINT fk_analytics_consents_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE analytics_events (
  id BIGINT NOT NULL AUTO_INCREMENT,
  event_id CHAR(36) NOT NULL,
  subject_key CHAR(64) NOT NULL,
  session_key CHAR(64) NOT NULL,
  campaign_id BIGINT NULL,
  data_scope VARCHAR(16) NOT NULL DEFAULT 'pilot',
  event_name VARCHAR(64) NOT NULL,
  event_version INT NOT NULL DEFAULT 1,
  outcome VARCHAR(16) NULL,
  failure_code VARCHAR(32) NULL,
  route_path VARCHAR(255) NULL,
  properties JSON NULL,
  occurred_at DATETIME(3) NOT NULL,
  received_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_analytics_events_subject_event (subject_key, event_id),
  KEY idx_analytics_events_campaign_name_time (campaign_id, event_name, occurred_at),
  KEY idx_analytics_events_name_time (event_name, occurred_at),
  KEY idx_analytics_events_subject_session_time (subject_key, session_key, occurred_at),
  KEY idx_analytics_events_retention (received_at),
  CONSTRAINT fk_analytics_events_subject FOREIGN KEY (subject_key) REFERENCES analytics_consents (subject_key) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_analytics_events_campaign FOREIGN KEY (campaign_id) REFERENCES evaluation_campaigns (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE evaluation_responses (
  id BIGINT NOT NULL AUTO_INCREMENT,
  campaign_id BIGINT NOT NULL,
  user_id INT NOT NULL,
  client_submission_id CHAR(36) NOT NULL,
  response_status VARCHAR(16) NOT NULL DEFAULT 'submitted',
  respondent_type VARCHAR(32) NULL,
  experience_level VARCHAR(32) NULL,
  primary_device VARCHAR(32) NULL,
  sus_answers JSON NULL,
  sus_score DECIMAL(5,2) NULL,
  task_results JSON NULL,
  open_feedback TEXT NULL,
  submitted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  withdrawn_at TIMESTAMP NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_evaluation_responses_campaign_user (campaign_id, user_id),
  UNIQUE KEY uq_evaluation_responses_user_submission (user_id, client_submission_id),
  KEY idx_evaluation_responses_campaign_status_time (campaign_id, response_status, submitted_at),
  KEY idx_evaluation_responses_campaign_demographics (campaign_id, respondent_type, experience_level, primary_device),
  KEY idx_evaluation_responses_user_time (user_id, submitted_at),
  CONSTRAINT fk_evaluation_responses_campaign FOREIGN KEY (campaign_id) REFERENCES evaluation_campaigns (id) ON DELETE CASCADE,
  CONSTRAINT fk_evaluation_responses_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE feedback_submissions (
  id BIGINT NOT NULL AUTO_INCREMENT,
  user_id INT NOT NULL,
  campaign_id BIGINT NULL,
  client_submission_id CHAR(36) NOT NULL,
  data_scope VARCHAR(16) NOT NULL DEFAULT 'pilot',
  category VARCHAR(32) NOT NULL,
  rating TINYINT NULL,
  details TEXT NOT NULL,
  route_path VARCHAR(255) NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'new',
  priority VARCHAR(16) NOT NULL DEFAULT 'normal',
  issue_theme VARCHAR(64) NULL,
  internal_note TEXT NULL,
  updated_by INT NULL,
  resolved_at TIMESTAMP NULL,
  retention_until TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_feedback_submissions_user_submission (user_id, client_submission_id),
  KEY idx_feedback_submissions_user_time (user_id, created_at),
  KEY idx_feedback_submissions_campaign_status_priority (campaign_id, status, priority, created_at),
  KEY idx_feedback_submissions_theme_time (issue_theme, created_at),
  KEY idx_feedback_submissions_retention (retention_until),
  KEY idx_feedback_submissions_updated_by (updated_by),
  CONSTRAINT fk_feedback_submissions_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_feedback_submissions_campaign FOREIGN KEY (campaign_id) REFERENCES evaluation_campaigns (id) ON DELETE CASCADE,
  CONSTRAINT fk_feedback_submissions_updated_by FOREIGN KEY (updated_by) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
